### ISSUE TITLE
more helpful errors, to help end users

### ISSUE THREAD

**Issue by thopri** [NOC-MSM/pyBDY#53]
PyNEMO at the moment can return unhelpful error messages that don't help end user. E.g. for the benchmark test if ln_dyn_2d is set to true then PyNEMO will crash with an indexing error of an array.

This is due to their being no SSH data that PyNEMO is expecting. However it is not clear from the stack trace or log file that this is the problem.

**Comment by rdPatmore** [comment]
This issue is a bit open ended. I will tag it with the error_handlling branch, but I will close it after short progress. Specific actions to follow.

**Comment by jpolton** [comment]
Have a look in the Pull Request (#71). This is a draft PR which I created to spot the difference between the code dev in "The IMMERSE branch" and the Master. The IMMERSE branch is an example of some dev was too large to be one ticket (and be reviewed in one go). It also introduced a bunch of hardwiring... So instead of merging we cherry pick bits now and there.

Anyway it has some logging edits that you might want to copy. (Search for "logging")

**Comment by rdPatmore** [comment]
Ok, good to know. I will investigate IMMERSE.

I would like to keep the scope of this issue quite small. If I find that the logging stuff in immerse is a big change and/or unique from what I am working on here, I might make a seperate issue with defined logging-IMMERSE tasks.

**Comment by rdPatmore** [comment]
Tasks:

- [ ] set warning for non-uniform time steps
- [ ] add warning if using annual means (details in TO DO of time_interpolation() )
- [ ] either add IMMERSE logging tasks or create new issue for these
- [ ] Test changes are sensible
